### ISSUE TITLE
パターンが決まっているものは、カスタムタイプで

### ISSUE THREAD

**Issue by ababup1192** [natsumisawa/elm-warota#2]
https://github.com/natsumisawa/elm-warota/blob/master/src/Main.elm#L22

パターンが有限のものは、漏れが検知できるように カスタムタイプを用いると良い。
https://guide.elm-lang.jp/appendix/types_as_sets.html
このページめっちゃオススメ

例: 

```elm
type Face = Neutral | Ninmari

faceToString face =
   case face of
      Neutral -> "neutrala"
      Ninmari -> "ninmari"


view =
   img [ src <| "face-" ++ faceToString face ++ ".png" ]
```

**Comment by natsumisawa** [comment]
まだこの章読んでなかった！ありがとうございます。とても良い章だった。

**Comment by natsumisawa** [comment]
数字で扱っているから、変更やランダムの処理が楽になっている側面も有り・・・どうするのがベストか考えてみます！
